In [2]:
import numpy as np
import numpy.ma as ma

import matplotlib.pyplot as plt

import csv

from astropy.io import ascii

In [10]:
f_iso = ascii.read('iso_mini.csv','r')
chi2_iso = f_iso['chi2'].data
chi2_iso

array([ 34.01136626,   5.87046714, 154.10952802, ...,          nan,
                nan,          nan])

In [15]:
no_fit_count_iso = 0
for i in range(len(chi2_iso)):
    if np.isnan(chi2_iso[i]):
        no_fit_count_iso += 1
no_fit_count_iso

8813

In [24]:
bad_fit_count_iso = 0
for i in range(len(chi2_iso)):
    if chi2_iso[i] >= 150:
        bad_fit_count_iso += 1
bad_fit_count_iso

638

In [12]:
bad_fit_count_iso = 0
for i in range(len(chi2_iso)):
    if chi2_iso[i] >= 200:
        bad_fit_count_iso += 1
bad_fit_count_iso

530

In [6]:
f_nfw = ascii.read('nfw_mini.csv','r')
chi2_nfw = f_nfw['chi2'].data
chi2_nfw

array([41.33709406,  6.58158482, 50.67156935, ...,         nan,
               nan,         nan])

In [16]:
no_fit_count_nfw = 0
for i in range(len(chi2_nfw)):
    if np.isnan(chi2_nfw[i]):
        no_fit_count_nfw += 1
no_fit_count_nfw

8813

In [25]:
bad_fit_count_nfw = 0
for i in range(len(chi2_nfw)):
    if chi2_nfw[i] >= 150:
        bad_fit_count_nfw += 1
bad_fit_count_nfw

526

In [26]:
bad_fit_count_nfw = 0
for i in range(len(chi2_nfw)):
    if chi2_nfw[i] >= 200:
        bad_fit_count_nfw += 1
bad_fit_count_nfw

416

In [18]:
f_bur = ascii.read('bur_mini.csv','r')
chi2_bur = f_bur['chi2'].data
chi2_bur

array([33.89159087,  6.0438397 , 47.67803286, ...,         nan,
               nan,         nan])

In [19]:
no_fit_count_bur = 0
for i in range(len(chi2_bur)):
    if np.isnan(chi2_bur[i]):
        no_fit_count_bur += 1
no_fit_count_bur

8813

In [27]:
bad_fit_count_bur = 0
for i in range(len(chi2_bur)):
    if chi2_bur[i] >= 150:
        bad_fit_count_bur += 1
bad_fit_count_bur

647

In [20]:
bad_fit_count_bur = 0
for i in range(len(chi2_bur)):
    if chi2_bur[i] >= 200:
        bad_fit_count_bur += 1
bad_fit_count_bur

542

In [22]:
len(chi2_iso) - no_fit_count_iso

2460

In [23]:
len(chi2_iso)

11273